name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Todos los días a medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3.1.0
        with:
          github_user_name: camiladuenas-dev
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "Genera snake.svg 🐍"
          add: "dist/github-contribution-grid-snake.svg"
